workflows:
  android-debug:
    name: Build Android Debug APK

    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - chmod +x gradlew
      - ./gradlew clean
      - ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    publishing:
      email:
        recipients:
          - your-email@example.com
